# Generated by Django 6.0.7 on 2026-07-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
