# Generated by Django 6.0.7 on 2026-07-22 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_category_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='Indian', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default='30-40 mins', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offer',
            field=models.CharField(default='20% OFF', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
